# one big testbed for lunamals, spins up all the services and dependencies necessary in one go
version: '3'
services:
  db:
    image: couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  cache:
    image: redis
    ports:
      - 6379:6379
  consul:
    image: consul
    ports:
      - 8500:8500
      - 8600:8600
  events:
    image: rabbitmq:3.7-management-alpine
    ports:
      - 8080:15672
      - 5672:5672
  jenkins:
    image: jenkins
  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
